// 加载依赖 - detection.js 中已定义 MOVE_STATE, ELEMENT_STATE
eval(file.readTextSync("calculate.js"));
eval(file.readTextSync("detection.js"));

// 常量定义
const HUD_ID = "PathRecorderHUD";

// 移动模式常量（detection.js 未定义此常量）
const MOVE_MODES = {
    WALK: "walk",
    DASH: "dash",
    FLY: "fly",
    CLIMB: "climb",
    SWIM: "swim",
    JUMP: "jump"
};

const CACHE_FOLDER = "process/_cache";
const CACHE_META = `${CACHE_FOLDER}/meta.json`;

const HUD_WIDTH = 800;
const HUD_HEIGHT = 400;
const TELEPORT_THRESHOLD = 20; // 传送检测阈值
const ANOMALY_THRESHOLD = 1000; // 异常距离阈值
const MAX_RECORDING_CYCLES = 72000; // 最大循环次数 (约10小时)
const strategyScript = "w(5)"; // 默认战斗策略脚本

// 配置读取 - 使用 let 以支持运行时修改
let questName = settings.questName || "Task";
let questLocation = settings.questLocation || "Mondstadt";
const author = settings.author || "User";
const autoFight = settings.autoFight !== false; // 默认启用自动战斗

// 快捷键配置
const keyRecord = settings.keyRecord || "F7";      // 开始/结束录制
const keyOcr = settings.keyOcr || "D9";            // OCR对话
const keyFight = settings.keyFight || "F8";        // 战斗标记
const keyExport = settings.keyExport || "F9";      // 导出/结束录制
const keyTeleportStart = settings.keyTeleportStart || "D8"; // 以传送点开始录制

// 游戏菜单映射 (用于检测特定界面) - 延迟获取避免加载顺序问题
function getMenuStateMap() {
    return {
        "角色C": ELEMENT_STATE.C,
        "背包B": ELEMENT_STATE.B,
        "教程G": ELEMENT_STATE.G,
        "好友O": ELEMENT_STATE.O,
        "任务J": ELEMENT_STATE.J,
        "联机F2": ELEMENT_STATE.F2,
        "祈愿F3": ELEMENT_STATE.F3,
        "纪行F4": ELEMENT_STATE.F4
    };
}

// 快捷键配置显示
const keysConfig = [
    { key: keyRecord, label: '开始/结束', active: false },
    { key: keyTeleportStart, label: '传送点开始', active: false, visible: true },
    { key: keyOcr, label: 'OCR对话', active: false },
    { key: keyFight, label: '战斗标记', active: false },
    { key: keyExport, label: '导出', active: false },
    { key: '0', label: '缩小', active: false }
];

// 全局状态
let isRecording = false;
let isProcessingAction = false; // 操作互斥锁，防止快捷键回调与主循环竞态
let lastEndType = null; // 上次录制结束类型: 'fight', 'dialogue', 'save', 'story'
let justExitedMap = false; // 是否刚从地图界面退出
let wasInMap = false; // 是否曾进入地图界面
let cycleCount = 0; // 循环计数器

let currentTrackData = {
    info: {
        name: questName,
        type: "collect",
        author: author,
        version: "1.0",
        description: "Generated by PathRecorder",
        map_name: "Teyvat",
        bgi_version: "0.47.2"
    },
    positions: []
};
let steps = []; // 存储所有步骤 { name, type, data, info }
let currentStepIndex = 1;

let lastPosition = null;
let currentPos = { x: 0, y: 0 };
let lastUpdateHUD = 0;
let lastSentHudData = "";
let lastSentStepCount = -1;
let stepsDirty = false;

// process.json 数据（仅在导出时使用）
let processData = [];

// === 缓存管理函数 ===

function saveCacheMeta() {
    const meta = {
        questName, questLocation, author,
        currentStepIndex, lastEndType,
        steps: steps
    };
    file.writeTextSync(CACHE_META, JSON.stringify(meta, null, 2));
}

function loadCacheMeta() {
    try {
        const content = file.readTextSync(CACHE_META);
        if (content && content.trim()) return JSON.parse(content);
    } catch (e) {}
    return null;
}

function clearCache() {
    // BGI 的 file API 不支持删除文件，改用标志位方式
    // 旧的 track-*.json 文件无害，新录制会从 track-1 开始覆盖
    file.writeTextSync(CACHE_META, JSON.stringify({ cleared: true }));
}

// 初始化录制数据（从缓存加载或全新开始）
async function initProcessData() {
    const meta = loadCacheMeta();

    if (meta && !meta.cleared) {
        // 有未导出的缓存数据，恢复会话
        questName = meta.questName || questName;
        questLocation = meta.questLocation || questLocation;
        currentStepIndex = meta.currentStepIndex || 1;
        lastEndType = meta.lastEndType || null;
        steps = meta.steps || [];
        stepsDirty = true;
        log.info(`从缓存恢复录制会话，共 ${steps.length} 个步骤，下一段: ${currentStepIndex}`);
    } else {
        // 全新录制
        steps = [];
        currentStepIndex = 1;
        lastEndType = null;
        log.info("开始新的录制会话");
    }

    // processData 不再在录制期间维护，仅在导出时生成
    processData = [];
}

// 键鼠钩子
let hook = null;
let uiPollTimer = null;

// 初始化
async function init() {
    log.info("=== PathRecorder 路径录制系统 ===");

    // 0. 加载已有的process.json (支持继续录制)
    await initProcessData();

    // 显示当前状态
    const isFirstRecording = (currentStepIndex === 1 && lastEndType === null);
    if (isFirstRecording) {
        log.info("当前状态: 全新录制，从第1段开始");
    } else {
        log.info(`当前状态: 继续录制，从第${currentStepIndex}段开始`);
        if (lastEndType) {
            const endTypeNames = {
                'fight': '战斗',
                'dialogue': '对话',
                'save': '保存',
                'story': '剧情'
            };
            log.info(`上次结束类型: ${endTypeNames[lastEndType] || lastEndType}`);
        }
    }

    // 1. 创建HUD（优先显示界面，让用户知道脚本已启动）
    log.info("创建 HTML HUD 面板...");
    htmlPanel.create(HUD_ID, HUD_WIDTH, HUD_HEIGHT);
    const htmlContent = file.readTextSync("status.html");
    htmlPanel.loadHtml(HUD_ID, htmlContent);
    htmlPanel.setLocked(HUD_ID, false);
    htmlPanel.setPosition(HUD_ID, 10, 10);
    htmlPanel.show(HUD_ID);

    // 给系统一点时间响应
    await sleep(100);

    // 2. 注册键鼠钩子（分步骤，避免阻塞）
    log.info("注册快捷键...");
    await sleep(50); // 让日志显示出来
    hook = new KeyMouseHook();
    await sleep(100); // 钩子初始化后给系统响应时间
    registerHotkeys();

    // 3. 延迟启用自动功能（非关键，可以稍后启用）
    await sleep(100);
    log.info("启用自动功能: AutoSkip / AutoPick / AutoEat");
    dispatcher.addTrigger(new RealtimeTimer("AutoSkip"));
    await sleep(50);
    dispatcher.addTrigger(new RealtimeTimer("AutoPick"));
    await sleep(50);
    dispatcher.addTrigger(new RealtimeTimer("AutoEat"));

    // 4. 显示快捷键说明
    log.info("=== 快捷键说明 ===");
    log.info(`${keyRecord}: 开始/结束录制`);
    log.info(`${keyTeleportStart}: 以传送点开始录制`);
    log.info(`${keyOcr}: OCR对话标记`);
    log.info(`${keyFight}: 战斗标记`);
    log.info(`${keyExport}: 导出`);
    log.info("0: 缩小/恢复HUD");
    log.info("====================");

    // 5. 启动主循环
    log.info("启动主循环，等待用户操作...");
    await mainLoop();
}

// 注册快捷键
function registerHotkeys() {
    hook.OnKeyDown((keyCode) => {
        switch (keyCode) {
            case keyRecord:
                toggleRecording();
                break;
            case keyTeleportStart:
                handleTeleportStart();
                break;
            case keyOcr:
                handleDialogue();
                break;
            case keyFight:
                handleFight();
                break;
            case keyExport:
                handleEndRecording();
                break;
            case 'D0':
                toggleHUD();
                break;
        }
    });
}

function updateKeysStatus() {
    keysConfig[0].active = isRecording;
    // 传送点开始按键：录制中隐藏且禁用
    keysConfig[1].visible = !isRecording;
    // 缩小按键：缩小状态下隐藏（由minimized-actions中的恢复窗口替代）
    keysConfig[5].visible = !isMinimized;
}

// 切换录制状态 (开始/结束)
async function toggleRecording() {
    if (isProcessingAction) return;
    isProcessingAction = true;
    try {
        if (isRecording) {
            // 正在录制 -> 结束录制
            await handleStopRecording();
        } else {
            // 未录制 -> 开始录制
            await handleResume();
        }
    } finally {
        isProcessingAction = false;
    }
}

// 结束录制（保存当前路径，停止录制）
async function handleStopRecording() {
    if (!isRecording) return;

    log.info("结束录制...");

    // 保存当前路径
    if (currentTrackData.positions.length > 0) {
        const result = await saveCurrentPath();
        if (result) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, result.filename, result.startPos, result.endPos);
        }
    }

    lastEndType = 'save';
    isRecording = false;
    saveCacheMeta();

    updateHUD();
    log.info("录制已结束，按 " + keyRecord + " 重新开始，按 " + keyExport + " 导出");
}

// 处理开始录制
async function handleResume() {
    log.info("开始录制...");

    // 确保在主界面
    if (!isInMainUI()) {
        await genshin.returnMainUi();
        await sleep(300);
    }

    if (!isInMainUI()) {
        log.warn("不在主界面，无法开始录制");
        return;
    }

    // 开始新的录制段
    await startNewRecording();

    isRecording = true;
    lastEndType = null;

    updateHUD();

    log.info(`录制已开始，文件段: ${currentStepIndex}`);
}

// 以传送点开始录制（一次性功能：打开大地图获取精确坐标后开始录制）
async function handleTeleportStart() {
    if (isProcessingAction || isRecording) return;
    isProcessingAction = true;
    try {
        log.info("以传送点开始录制...");

        // 确保在主界面
        if (!isInMainUI()) {
            await genshin.returnMainUi();
            await sleep(300);
        }

        if (!isInMainUI()) {
            log.warn("不在主界面，无法开始录制");
            return;
        }

        // 打开大地图获取精确坐标
        keyPress("M");
        await sleep(500);

        let bigMapPosition = null;
        let retryCount = 0;

        while (retryCount < 3 && !bigMapPosition) {
            try {
                bigMapPosition = genshin.getPositionFromBigMap();
                if (bigMapPosition && bigMapPosition.X !== 0 && bigMapPosition.Y !== 0) {
                    log.info(`大地图精确坐标: (${bigMapPosition.X.toFixed(3)}, ${bigMapPosition.Y.toFixed(3)})`);
                    break;
                } else {
                    throw new Error("获取到无效坐标");
                }
            } catch (error) {
                retryCount++;
                if (retryCount < 3) await sleep(200);
            }
        }

        // 返回主界面
        await genshin.returnMainUi();
        await sleep(200);

        // 确定使用的坐标
        let startX, startY;
        if (bigMapPosition && bigMapPosition.X !== 0 && bigMapPosition.Y !== 0) {
            startX = bigMapPosition.X;
            startY = bigMapPosition.Y;
        } else {
            // 大地图获取失败，回退到小地图
            log.warn("大地图坐标获取失败，使用小地图坐标");
            const fallback = genshin.getPositionFromMap();
            if (fallback.X === 0 && fallback.Y === 0) {
                log.warn("无法获取当前位置");
                return;
            }
            startX = fallback.X;
            startY = fallback.Y;
        }

        // 检测初始状态
        const initialState = await checkAbnormalState();

        // 添加传送点作为起始点
        const startPoint = {
            id: currentTrackData.positions.length + 1,
            x: startX,
            y: startY,
            action: "",
            move_mode: "walk",
            action_params: "",
            type: "teleport",
            optimize: false,
            state: initialState,
            timestamp: Date.now()
        };

        currentTrackData.positions.push(startPoint);
        lastPosition = { x: startX, y: startY };

        isRecording = true;
        lastEndType = null;

        updateHUD();
        log.info(`以传送点开始录制: 坐标=(${startX.toFixed(1)}, ${startY.toFixed(1)})，文件段: ${currentStepIndex}`);
    } finally {
        isProcessingAction = false;
    }
}

// 开始新的录制段
async function startNewRecording() {
    log.info("开始新的录制段...");

    // 获取当前位置
    const position = genshin.getPositionFromMap();
    if (position.X === 0 && position.Y === 0) {
        log.warn("无法获取当前位置");
        return;
    }

    // 判断起始点类型
    const isFirstRecording = (currentStepIndex === 1);
    let initialPointType = "path";

    if (isFirstRecording && settings.forceTpFirst) {
        initialPointType = "teleport";
        log.info("起点设置为传送点");
    }

    // 检测初始状态
    const initialState = await checkAbnormalState();

    // 添加起始点
    const startPoint = {
        id: currentTrackData.positions.length + 1,
        x: position.X,
        y: position.Y,
        action: "",
        move_mode: "walk",
        action_params: "",
        type: initialPointType,
        state: initialState,
        timestamp: Date.now()
    };

    if (initialPointType === "teleport") {
        startPoint.optimize = false;
    }

    currentTrackData.positions.push(startPoint);
    lastPosition = { x: position.X, y: position.Y };

    log.info(`新录制段开始: 类型=${initialPointType}, 坐标=(${position.X.toFixed(1)}, ${position.Y.toFixed(1)})`);
}

// 处理对话功能 (完整版: OCR + 点击NPC)
async function handleDialogue() {
    if (isProcessingAction) return;
    isProcessingAction = true;
    try {
        if (!isRecording) {
            log.warn("未在录制状态，无法添加对话标记");
            return;
        }

    log.info("处理对话功能...");

    // 临时停止录制
    const wasRecording = isRecording;
    isRecording = false;

    // 保存当前路径
    if (currentTrackData.positions.length > 0) {
        const result = await saveCurrentPath();
        if (result) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, result.filename, result.startPos, result.endPos);
        }
    }

    // 确保在主界面
    await genshin.returnMainUi();
    await sleep(200);

    // 从游戏界面OCR提取NPC名称
    const npcName = await extractNPCNameFromTask();

    if (npcName) {
        log.info(`提取到NPC名称: ${npcName}`);

        // 尝试在对话区域找到并点击NPC
        const dialogRegion = { X: 1150, Y: 300, WIDTH: 350, HEIGHT: 400 };
        let dialogResults = await Utils.easyOCR(dialogRegion);

        for (let i = 0; i < dialogResults.count; i++) {
            let text = dialogResults[i].text;
            let res = dialogResults[i];
            if (text.includes(npcName)) {
                log.info(`点击NPC选项: ${text}`);
                keyDown("VK_MENU");
                await sleep(500);
                click(res.x, res.y);
                leftButtonClick();
                keyUp("VK_MENU");
                break;
            }
        }

        addStepToList('ocr', `Talk: ${npcName}`, `对话 ${npcName}`);
    } else {
        log.warn("未能提取到NPC名称，添加默认对话指令");
        addStepToList('ocr', '对话', '对话');
    }

    // 按F键触发剧情
    log.info("按下F键触发剧情");
    keyPress("F");
    await sleep(500);

    saveCacheMeta();
    lastEndType = 'dialogue';

    updateHUD();
    log.info("对话标记已添加，等待剧情结束...");

    // 等待返回主界面
    await waitForMainUI();

    // 自动恢复录制
    if (wasRecording) {
        isRecording = true;
        lastEndType = null;
        await startNewRecording();
        log.info("从对话返回，自动恢复录制");
    }

    updateHUD();
    } finally {
        isProcessingAction = false;
    }
}

// 处理战斗功能 (完整版: 标记 + 自动战斗)
async function handleFight() {
    if (isProcessingAction) return;
    isProcessingAction = true;
    try {
        if (!isRecording) {
            log.warn("未在录制状态，无法添加战斗标记");
            return;
        }

        log.info("处理战斗功能...");

        // 保存当前路径
        await genshin.returnMainUi();

        if (currentTrackData.positions.length > 0) {
            const result = await saveCurrentPath();
            if (result) {
                addStepToList('move', `Path ${currentStepIndex - 1}`, result.filename, result.startPos, result.endPos);
            }
        }

        // 添加战斗标记
        let pos = { x: 0, y: 0 };
        try {
            const p = genshin.getPositionFromMap();
            pos = { x: p.X, y: p.Y };
        } catch (e) { }

        addStepToList('fight', 'Combat Event', null, pos, pos);
        saveCacheMeta();

        lastEndType = 'fight';
        isRecording = false;

        updateHUD();
        log.info("战斗标记已添加");

        // 如果启用自动战斗，执行战斗并自动恢复录制
        if (autoFight) {
            log.info("启动自动战斗...");
            try {
                await dispatcher.runTask(new SoloTask("AutoFight"));
                log.info("自动战斗完成");
            } catch (e) {
                log.error("自动战斗出错: " + e.message);
            }

            // 等待返回主界面
            await waitForMainUI();

            // 自动恢复录制
            isRecording = true;
            lastEndType = null;
            await startNewRecording();
            log.info("战斗结束，自动恢复录制");
            updateHUD();
        } else {
            // 未启用自动战斗，需要用户手动恢复
            log.info("战斗结束，按 " + keyRecord + " 恢复录制");
        }
    } finally {
        isProcessingAction = false;
    }
}

// 处理结束录制/导出
async function handleEndRecording() {
    if (isProcessingAction) return;
    isProcessingAction = true;
    try {
        log.info("导出录制数据...");

        // 保存最后的路径（如有）
        if (currentTrackData.positions.length > 0) {
            const result = await saveCurrentPath();
            if (result) {
                addStepToList('move', `Path ${currentStepIndex - 1}`, result.filename, result.startPos, result.endPos);
            }
        }

        // 生成最终目录
        const exportFolder = `process/${questLocation}/${questName}`;

        // 从 steps 生成 processData 并导出
        processData = [`作者：${author}`];
        let trackIndex = 1;

        for (const step of steps) {
            if (step.type === 'move') {
                // 从缓存读取路径文件
                const cacheFile = `${CACHE_FOLDER}/${step.data}`;
                const finalName = step.nameModified ? step.name : `${questName}-${trackIndex}`;
                const finalFilename = `${finalName}.json`;
                const finalPath = `${exportFolder}/${finalFilename}`;

                try {
                    const trackContent = file.readTextSync(cacheFile);
                    if (trackContent) {
                        // 更新文件头中的 name
                        const trackData = JSON.parse(trackContent);
                        trackData.info.name = finalName;
                        file.writeTextSync(finalPath, JSON.stringify(trackData, null, 2));
                    }
                } catch (e) {
                    log.error(`导出路径文件失败: ${step.data} -> ${e.message}`);
                }

                processData.push(`地图追踪 ${finalFilename}`);
                step.data = finalFilename; // 更新步骤中的文件名
                trackIndex++;
            } else if (step.type === 'fight') {
                processData.push('战斗');
            } else if (step.type === 'ocr') {
                processData.push(step.data); // "对话 NPC名"
            } else if (step.type === 'story') {
                processData.push('等待返回主界面');
            }
        }

        // 保存 process.json 到最终目录
        const processPath = `${exportFolder}/process.json`;
        file.writeTextSync(processPath, processData.join('\n'));

        // 清理缓存
        clearCache();

        lastEndType = 'save';
        isRecording = false;

        updateHUD();
        notification.send(`PathRecorder: 已导出到 ${exportFolder}/`);
        log.info("=== 录制已导出 ===");
        log.info(`保存位置: ${exportFolder}/`);
        log.info(`共 ${steps.length} 个步骤，${trackIndex - 1} 个路径文件`);
    } finally {
        isProcessingAction = false;
    }
}

// 处理剧情界面
async function handleStoryInterface() {
    log.info("检测到剧情界面，处理特殊逻辑...");

    if (currentTrackData.positions.length > 0) {
        // 在最后一个路径点添加combat_script动作
        const lastIdx = currentTrackData.positions.length - 1;
        currentTrackData.positions[lastIdx].action = "combat_script";
        currentTrackData.positions[lastIdx].action_params = strategyScript;
        currentTrackData.positions[lastIdx].optimize = false;

        // 保存当前路径
        const result = await saveCurrentPath();
        if (result) {
            addStepToList('move', `Path ${currentStepIndex - 1} (Story)`, result.filename, result.startPos, result.endPos);
        }
    }

    addStepToList('story', 'Wait MainUI', null);
    saveCacheMeta();

    lastEndType = 'story';
    isRecording = false;

    log.info("剧情界面处理完成，等待返回主界面");
    updateHUD();

    // 等待返回主界面
    await waitForMainUI();

    // 自动恢复录制
    log.info("从剧情返回主界面，自动恢复录制");
    isRecording = true;
    lastEndType = null;
    lastPosition = null;
    await startNewRecording();

    updateHUD();
}

// 等待返回主界面
async function waitForMainUI() {
    log.info("等待返回主界面...");

    for (let i = 0; i < 1200; i++) { // 最多等待10分钟
        if (isInMainUI()) {
            log.info("已返回主界面");
            return true;
        }
        await sleep(500);
    }

    log.warn("等待返回主界面超时");
    return false;
}

// 添加步骤到列表
function addStepToList(type, name, data, startPos = null, endPos = null) {
    const step = {
        id: Date.now() + Math.random(),
        name: name,
        type: type,
        data: data,
        nameModified: false,
        start: startPos ? [startPos.x?.toFixed(0) || '?', startPos.y?.toFixed(0) || '?'] : ['?', '?'],
        end: endPos ? [endPos.x?.toFixed(0) || '?', endPos.y?.toFixed(0) || '?'] : ['?', '?']
    };
    steps.push(step);
    stepsDirty = true;
}

// 缩小/恢复HUD
let isMinimized = false;
function toggleHUD() {
    isMinimized = !isMinimized;
    if (!isMinimized) {
        // 恢复完整模式时解除锁定，确保可交互
        htmlPanel.setLocked(HUD_ID, false);
    }
    updateHUD();
}

// 保存当前路径到缓存文件
async function saveCurrentPath() {
    if (currentTrackData.positions.length === 0) return null;

    // 捕获起止坐标（在清空前）
    const startPos = currentTrackData.positions[0];
    const endPos = currentTrackData.positions[currentTrackData.positions.length - 1];

    // 路径优化
    await processTrackData();

    const cacheFilename = `track-${currentStepIndex}.json`;
    const cachePath = `${CACHE_FOLDER}/${cacheFilename}`;

    // 更新文件头信息
    currentTrackData.info.name = `track-${currentStepIndex}`;

    file.writeTextSync(cachePath, JSON.stringify(currentTrackData, null, 2));

    // 重置数据
    currentTrackData.positions = [];
    lastPosition = null;
    currentStepIndex++;

    return {
        filename: cacheFilename,
        startPos: { x: startPos.x, y: startPos.y },
        endPos: { x: endPos.x, y: endPos.y }
    };
}

// 处理收集到的路径数据
async function processTrackData() {
    log.info("处理路径数据...");

    // 1. 先优化点
    optimizePathPoints();

    // 2. 处理移动模式
    processMoveModes();

    // 3. 清理临时状态属性
    for (const pos of currentTrackData.positions) {
        delete pos.state;
        delete pos.timestamp;
        delete pos.__climb_points_count;
    }

    log.info("路径数据处理完成");
}

// 完整的移动模式处理
function processMoveModes() {
    log.info("处理移动模式和动作...");

    const positions = currentTrackData.positions;
    if (!positions || positions.length === 0) return;

    // 重置动作（保留 optimize=false 的点）
    for (const pos of positions) {
        if (pos.optimize !== false) {
            pos.action = "";
        }
    }

    // 分段处理飞行/游泳/攀爬
    let i = 0;
    while (i < positions.length) {
        const currentState = positions[i].state;

        // 飞行段：设置 fly 模式，终点添加 stop_flying
        if (currentState === MOVE_STATE.FLY) {
            let end = i;
            while (end + 1 < positions.length && positions[end + 1].state === MOVE_STATE.FLY) end++;
            for (let k = i; k <= end; k++) positions[k].move_mode = MOVE_MODES.FLY;
            positions[end].action = "stop_flying";
            log.debug(`飞行段: ${i} - ${end}, 添加stop_flying`);
            i = end + 1;
            continue;
        }

        // 游泳段：设置 swim 模式
        if (currentState === MOVE_STATE.SWIM) {
            let end = i;
            while (end + 1 < positions.length && positions[end + 1].state === MOVE_STATE.SWIM) end++;
            for (let k = i; k <= end; k++) positions[k].move_mode = MOVE_MODES.SWIM;
            log.debug(`游泳段: ${i} - ${end}`);
            i = end + 1;
            continue;
        }

        // 攀爬段：根据时长决定 jump 或 climb
        if (currentState === MOVE_STATE.CLIMB) {
            let end = i;
            while (end + 1 < positions.length && positions[end + 1].state === MOVE_STATE.CLIMB) end++;

            const climbPointsCount = positions[i].__climb_points_count || (end - i + 1);
            const climbDurationSeconds = climbPointsCount * 0.9;
            const climbMode = climbDurationSeconds < 15 ? MOVE_MODES.JUMP : MOVE_MODES.CLIMB;

            for (let k = i; k <= end; k++) positions[k].move_mode = climbMode;
            log.debug(`攀爬段: ${i} - ${end}, 时长=${climbDurationSeconds.toFixed(1)}s, 模式=${climbMode}`);

            // 长攀爬前回溯15单位，将dash改为walk
            if (climbMode === MOVE_MODES.CLIMB) {
                let backDistAccum = 0;
                for (let j = i - 1; j >= 0; j--) {
                    const segDist = distance(
                        { x: positions[j + 1].x, y: positions[j + 1].y },
                        { x: positions[j].x, y: positions[j].y }
                    );
                    backDistAccum += segDist;
                    if (backDistAccum >= 15) break;
                    if (positions[j].move_mode === MOVE_MODES.DASH) {
                        positions[j].move_mode = MOVE_MODES.WALK;
                    }
                }
            }

            i = end + 1;
            continue;
        }

        i++;
    }

    // 未设置模式的点根据距离判断dash/walk
    for (let idx = 0; idx < positions.length; idx++) {
        if (!positions[idx].move_mode || positions[idx].move_mode === "") {
            if (idx === 0) {
                positions[idx].move_mode = MOVE_MODES.WALK;
                continue;
            }
            const prev = positions[idx - 1];
            const dist = distance({ x: positions[idx].x, y: positions[idx].y }, { x: prev.x, y: prev.y });
            positions[idx].move_mode = dist > 10 ? MOVE_MODES.DASH : MOVE_MODES.WALK;
        }
    }
}

// 路径优化
function optimizePathPoints() {
    const positions = currentTrackData.positions;
    if (positions.length <= 2) return;

    const originalPoints = positions.map((p, index) => ({
        index: index,
        x: p.x,
        y: p.y,
        state: p.state
    }));

    // RDP简化
    const pointsForRdp = originalPoints.map(p => ({ x: p.x, y: p.y }));
    const simplified = rdp(pointsForRdp, 2.0);

    // 找出保留的点索引
    let keptIndices = simplified.map(sp => {
        return originalPoints.findIndex(op => op.x === sp.x && op.y === sp.y);
    }).filter(idx => idx !== -1);

    // 分段扫描，确保保留状态转换点
    const segments = [];
    let segStart = 0;
    for (let i = 1; i < originalPoints.length; i++) {
        if (originalPoints[i].state !== originalPoints[i - 1].state) {
            segments.push({ state: originalPoints[segStart].state, start: segStart, end: i - 1 });
            segStart = i;
        }
    }
    segments.push({ state: originalPoints[segStart].state, start: segStart, end: originalPoints.length - 1 });

    // 强制保留首尾
    if (!keptIndices.includes(0)) keptIndices.push(0);
    if (!keptIndices.includes(originalPoints.length - 1)) keptIndices.push(originalPoints.length - 1);

    // 强制保留传送点和不可优化点
    for (let idx = 0; idx < positions.length; idx++) {
        const pos = positions[idx];
        if (pos.type === "teleport" || pos.optimize === false) {
            if (!keptIndices.includes(idx)) {
                keptIndices.push(idx);
            }
        }
    }

    // 保留状态分段的起止点
    for (const seg of segments) {
        if (seg.state === MOVE_STATE.FLY || seg.state === MOVE_STATE.SWIM) {
            if (!keptIndices.includes(seg.start)) keptIndices.push(seg.start);
            if (!keptIndices.includes(seg.end)) keptIndices.push(seg.end);
        } else if (seg.state === MOVE_STATE.CLIMB) {
            if (!keptIndices.includes(seg.start)) keptIndices.push(seg.start);
            if (!keptIndices.includes(seg.end)) keptIndices.push(seg.end);
            // 移除攀爬段中间点
            keptIndices = keptIndices.filter(idx => !(idx > seg.start && idx < seg.end));
            // 记录攀爬点数
            positions[seg.start].__climb_points_count = seg.end - seg.start + 1;
        }
    }

    // 去重排序
    keptIndices = Array.from(new Set(keptIndices)).sort((a, b) => a - b);

    // 创建新数组
    const newPositions = keptIndices.map(idx => ({ ...positions[idx] }));
    newPositions.forEach((pos, idx) => { pos.id = idx + 1; });

    currentTrackData.positions = newPositions;
    log.info(`路径优化: ${positions.length} → ${newPositions.length} 个点`);
}

// 主循环
async function mainLoop() {
    while (cycleCount < MAX_RECORDING_CYCLES) {
        cycleCount++;

        // 每1000次输出进度
        if (cycleCount % 1000 === 0) {
            log.info(`系统运行: ${cycleCount}/${MAX_RECORDING_CYCLES} (${((cycleCount / MAX_RECORDING_CYCLES) * 100).toFixed(1)}%)`);
        }

        try {
            // 1. 处理 HTML 指令
            await handleClientActions();

            // 2. 单次截屏，用于本周期所有检测（5次截屏→1次）
            beginDetectionCycle();

            let elementState = ELEMENT_STATE.MAINUI;
            try {
                elementState = await checkElementStateLight();
            } catch (stateErr) {
                // 界面检测失败时使用默认值，避免阻塞
            }

            // 追踪地图状态
            if (elementState === ELEMENT_STATE.MAP) {
                wasInMap = true;
            } else if (wasInMap && !justExitedMap) {
                justExitedMap = true;
                wasInMap = false;
                log.info("检测到离开地图界面，设置传送检测标志");
            }

            // 3. 录制逻辑（复用同一张截图检测移动状态，避免重复截屏）
            // 用 elementState 判断主界面，不再重复调用 isInMainUI()
            if (isRecording && !isProcessingAction && elementState === ELEMENT_STATE.MAINUI) {
                try {
                    await recordPosition();
                } catch (recErr) {
                    // 录制出错时继续循环
                }
            }

            // 结束本周期检测缓存
            endDetectionCycle();

            // 4. 剧情界面处理（在缓存周期之外，waitForMainUI 每次检查需要实时截图）
            if (elementState === ELEMENT_STATE.Story) {
                if (isRecording) {
                    log.info("录制中检测到剧情界面");
                    await handleStoryInterface();
                } else {
                    log.info("非录制状态检测到剧情界面，等待返回主界面");
                    await waitForMainUI();
                }
            }

            // 5. 更新HUD
            if (Date.now() - lastUpdateHUD > 500) {
                await updateHUD();
                lastUpdateHUD = Date.now();
            }
        } catch (e) {
            endDetectionCycle();
            log.error("MainLoop Error: " + e.message);
        }

        // 确保每次循环都有延迟，避免死循环
        await sleep(500);
    }

    // 达到最大循环次数
    log.warn(`已达到最大运行次数限制 (${MAX_RECORDING_CYCLES})，自动保存并结束`);
    if (isRecording && currentTrackData.positions.length > 0) {
        const result = await saveCurrentPath();
        if (result) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, result.filename, result.startPos, result.endPos);
            saveCacheMeta();
        }
    }
}

// 记录坐标
async function recordPosition() {
    try {
        const position = genshin.getPositionFromMap();
        if (position.X === 0 && position.Y === 0) return;

        // 距离判定
        let dist = 0;
        if (lastPosition) {
            dist = distance({ x: position.X, y: position.Y }, lastPosition);
            if (dist < 1.0) return; // 距离太近不记录
        }

        // 检测移动状态（轻量级，跳过已确认的 isInMainUI 检查）
        const moveState = await checkMoveStateOnly();

        let pointType = "path";
        let optimizeFlag = true;

        // 从地图退出后的传送检测
        if (justExitedMap) {
            log.info(`刚从地图返回，检测首个点，距离: ${dist.toFixed(2)}`);

            if (dist > TELEPORT_THRESHOLD) {
                await autoSplitTeleport(position);
                justExitedMap = false;
                return;
            }

            justExitedMap = false;
        } else if (dist > ANOMALY_THRESHOLD && lastPosition) {
            // 异常距离检测（非地图退出情况）
            log.warn(`异常距离: ${dist.toFixed(2)} > ${ANOMALY_THRESHOLD}，可能是传送`);
            await autoSplitTeleport(position);
            return;
        }

        // 构建点数据
        const point = {
            id: currentTrackData.positions.length + 1,
            x: position.X,
            y: position.Y,
            action: "",
            move_mode: "dash",
            action_params: "",
            type: pointType,
            state: moveState,
            timestamp: Date.now()
        };

        if (!optimizeFlag) {
            point.optimize = false;
        }

        // 处理移动模式
        if (moveState === MOVE_STATE.FLY) point.move_mode = "fly";
        if (moveState === MOVE_STATE.CLIMB) point.move_mode = "climb";
        if (moveState === MOVE_STATE.SWIM) point.move_mode = "swim";

        currentTrackData.positions.push(point);
        lastPosition = { x: position.X, y: position.Y };

        log.debug(`记录点 #${point.id}: (${point.x.toFixed(1)}, ${point.y.toFixed(1)}) 状态=${moveState}`);

    } catch (e) {
        log.error("recordPosition Error: " + e.message);
    }
}

// 自动分段传送：保存当前路径，获取精确坐标，以传送点为起点开始新段
async function autoSplitTeleport(fallbackPos) {
    log.info("检测到传送，自动分段并以传送点开始新段...");

    // 保存当前路径作为一个步骤
    if (currentTrackData.positions.length > 0) {
        const result = await saveCurrentPath();
        if (result) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, result.filename, result.startPos, result.endPos);
            saveCacheMeta();
        }
    }

    // 打开大地图获取精确坐标
    keyPress("M");
    await sleep(500);

    let bigMapPosition = null;
    let retryCount = 0;

    while (retryCount < 3 && !bigMapPosition) {
        try {
            bigMapPosition = genshin.getPositionFromBigMap();
            if (bigMapPosition && bigMapPosition.X !== 0 && bigMapPosition.Y !== 0) {
                log.info(`大地图精确坐标: (${bigMapPosition.X.toFixed(3)}, ${bigMapPosition.Y.toFixed(3)})`);
                break;
            } else {
                throw new Error("获取到无效坐标");
            }
        } catch (error) {
            retryCount++;
            if (retryCount < 3) await sleep(200);
        }
    }

    await genshin.returnMainUi();
    await sleep(200);

    // 确定使用的坐标
    let tpX, tpY;
    if (bigMapPosition && bigMapPosition.X !== 0 && bigMapPosition.Y !== 0) {
        tpX = bigMapPosition.X;
        tpY = bigMapPosition.Y;
    } else if (fallbackPos) {
        tpX = fallbackPos.X || fallbackPos.x;
        tpY = fallbackPos.Y || fallbackPos.y;
    } else {
        const pos = genshin.getPositionFromMap();
        tpX = pos.X;
        tpY = pos.Y;
    }

    // 以传送点为起点开始新段
    const tpState = await checkAbnormalState();
    currentTrackData.positions.push({
        id: currentTrackData.positions.length + 1,
        x: tpX,
        y: tpY,
        action: "",
        move_mode: "walk",
        action_params: "",
        type: "teleport",
        optimize: false,
        state: tpState,
        timestamp: Date.now()
    });
    lastPosition = { x: tpX, y: tpY };

    notification.send("检测到传送，已自动分段");
    log.info(`传送点自动分段: (${tpX.toFixed(1)}, ${tpY.toFixed(1)})`);
    updateHUD();
}

// 处理客户端指令
async function handleClientActions() {
    try {
        const actionStr = await htmlPanel.eval(HUD_ID, "window.clientAction");
        let action = null;
        try {
            if (actionStr && actionStr !== "null") {
                action = JSON.parse(actionStr);
            }
        } catch (e) { }

        if (action) {
            log.info("Client Action: " + JSON.stringify(action));
            await htmlPanel.eval(HUD_ID, "window.clientAction = null");

            switch (action.type) {
                case 'delete_step':
                    const idx = steps.findIndex(s => s.id === action.id);
                    if (idx !== -1) {
                        steps.splice(idx, 1);
                        stepsDirty = true;
                        saveCacheMeta();
                        updateHUD();
                    }
                    break;
                case 'rename_step':
                    const step = steps.find(s => s.id === action.id);
                    if (step) {
                        step.name = action.newName;
                        step.nameModified = true;
                        stepsDirty = true;
                        saveCacheMeta();
                        updateHUD();
                    }
                    break;
                case 'update_task_name':
                    questName = action.name;
                    saveCacheMeta();
                    break;
                case 'undo':
                    if (steps.length > 0) {
                        steps.pop();
                        stepsDirty = true;
                        saveCacheMeta();
                        updateHUD();
                    }
                    break;
                case 'toggle_minimize':
                    isMinimized = !isMinimized;
                    if (!isMinimized) {
                        htmlPanel.setLocked(HUD_ID, false);
                    }
                    updateHUD();
                    break;
                case 'export':
                    handleEndRecording();
                    break;
            }
        }
    } catch (e) { }
}

// 更新HUD状态
let isUpdatingHUD = false;

async function updateHUD() {
    if (isUpdatingHUD) return;
    isUpdatingHUD = true;

    try {
        updateKeysStatus();

        let displayPos = currentPos;
        if (!lastPosition) {
            try {
                const p = genshin.getPositionFromMap();
                if (p.X !== 0) displayPos = { x: p.X, y: p.Y };
            } catch (e) { }
        } else {
            displayPos = lastPosition;
        }
        currentPos = displayPos;

        // 提取路径点用于地图绘制 (最多保留最近100个点避免数据过大)
        const pathPoints = currentTrackData.positions.slice(-100).map(p => ({
            x: p.x,
            y: p.y,
            type: p.type || 'path'
        }));

        const stateData = {
            isRecording: isRecording,
            lastEndType: lastEndType,
            taskName: questName,
            currentCoords: { x: displayPos.x, y: displayPos.y },
            keys: keysConfig.filter(k => k.visible !== false),
            cycleCount: cycleCount,
            pathPoints: pathPoints,
            isMinimized: isMinimized
        };

        if (steps.length !== lastSentStepCount || stepsDirty) {
            stateData.steps = steps.map(s => ({
                id: s.id,
                name: s.name,
                type: s.type,
                start: s.start,
                end: s.end
            }));
            lastSentStepCount = steps.length;
            stepsDirty = false;
        }

        const newStateStr = JSON.stringify(stateData);
        if (newStateStr !== lastSentHudData) {
            try {
                await htmlPanel.eval(HUD_ID, `updateState(${newStateStr})`);
                lastSentHudData = newStateStr;
            } catch (e) { }
        }
    } finally {
        isUpdatingHUD = false;
    }
}

// 脚本结束清理
function cleanUp() {
    if (hook) hook.Dispose();
    htmlPanel.closeAll();
    saveCacheMeta();
    log.info("缓存元数据已保存");
}

// 启动
(async () => {
    try {
        await init();
    } catch (e) {
        log.error("Init Error: " + e.message);
        cleanUp();
    }
})();
