// 加载依赖
eval(file.readTextSync("calculate.js"));
eval(file.readTextSync("detection.js"));

// 常量定义
const HUD_ID = "PathRecorderHUD";

// 定义移动状态常量 - 必须先定义
const MOVE_STATE = {
    NORMAL: "normal",
    FLY: "fly",
    CLIMB: "climb",
    SWIM: "swim",
    UNKNOWN: "unknown"
};

const MOVE_MODES = {
    WALK: "walk",
    DASH: "dash",
    FLY: "fly",
    CLIMB: "climb",
    SWIM: "swim",
    JUMP: "jump"
};
const HUD_WIDTH = 400;
const HUD_HEIGHT = 800; // 高度设大一点以容纳长列表
const TELEPORT_THRESHOLD = 50; // 传送检测阈值 (距离突变 > 50)
const ANOMALY_THRESHOLD = 1000; // 异常距离阈值

// 配置读取
const questName = settings.questName || "Task";
const questLocation = settings.questLocation || "Mondstadt";
const author = settings.author || "User";
const autoFight = settings.autoFight !== false;
const keyRecord = settings.keyRecord || "F7";
const keySplit = settings.keySplit || "F8";
const keyOcr = settings.keyOcr || "F9";
const keyFight = settings.keyFight || "F10";

const keysConfig = [
    { key: keyRecord, label: '录制/暂停', active: false },
    { key: keySplit, label: '路径分段', active: false },
    { key: keyOcr, label: 'OCR锚点', active: false },
    { key: keyFight, label: '战斗标记', active: false }
];

// 全局状态
let isRecording = false;
let isPaused = false; // 暂停状态 (例如传送检测触发)
let currentTrackData = {
    info: {
        name: questName,
        type: "collect",
        author: author,
        version: "1.0",
        description: "Generated by PathRecorder",
        map_name: "Teyvat",
        bgi_version: "0.45.0"
    },
    positions: []
};
let steps = []; // 存储所有步骤 { name, type, data, info }
let currentStepIndex = 1;

let lastPosition = null;
let currentPos = { x: 0, y: 0 }; // Initialize currentPos to avoid ReferenceError
let lastUpdateHUD = 0;
let lastSentHudData = ""; // Cache for diffing
let lastSentStepCount = -1; // Optimization for IPC
let stepsDirty = false; // Force update flag

// 键鼠钩子
let hook = null;
let uiPollTimer = null;

// 初始化
async function init() {
    log.info("Path Recorder Initializing...");

    // 0. 预热地图 (异步防止卡死)
    try {
        log.info("Warming up map resources (this may take a few seconds)...");
        await genshin.warmUpMapAsync();
        log.info("Map resources ready.");
    } catch (e) {
        log.error("Map warmup failed: " + e.message);
    }

    // 1. 创建HUD
    log.info("Creating HTML Panel...");
    htmlPanel.create(HUD_ID, HUD_WIDTH, HUD_HEIGHT);
    const htmlContent = file.readTextSync("status.html");

    log.info("Loading HTML Content...");
    htmlPanel.loadHtml(HUD_ID, htmlContent);

    // 等待 WebView2 初始化完成
    await sleep(500);

    // 设置HUD样式 (透明穿透 + 右侧停靠)
    // 注意：CSS中已设置 pointer-events: none 实现穿透，无需 SetLocked(true)，否则无法交互
    // 我们需要的是：背景透明，但列表区域可点击。这完全由HTML/CSS控制。
    htmlPanel.setLocked(HUD_ID, false); // 全局状态 - 适配新HTML
    htmlPanel.setPosition(HUD_ID, genshin.width - HUD_WIDTH - 20, 100);

    log.info("Showing HUD...");
    htmlPanel.show(HUD_ID);

    // 2. 注册键鼠钩子
    log.info("Registering hooks...");
    hook = new KeyMouseHook();
    registerHotkeys();

    // 3. 启动主循环
    log.info("Starting main loop...");
    await mainLoop();
}

// 注册快捷键
function registerHotkeys() {
    hook.OnKeyDown((keyCode) => {
        switch (keyCode) {
            case keyRecord:
                toggleRecording();
                break;
            case keySplit:
                splitSegment();
                break;
            case keyOcr:
                triggerOCR();
                break;
            case keyFight:
                addCombatMarker();
                break;
            case 'F12':
                toggleHUD();
                break;
        }
    });
}

function updateKeysStatus() {
    keysConfig[0].active = isRecording;
    // fleeting states for others? currently only recording is toggle-able
}

// 切换录制状态
function toggleRecording() {
    if (isPaused) {
        // 从暂停恢复
        isPaused = false;
        isRecording = true;
        log.info("Resumed recording.");
    } else {
        isRecording = !isRecording;
        if (isRecording) {
            log.info("Started recording.");
            // 每次开始录制时，重新获取当前位置作为起点
            lastPosition = null;
        } else {
            log.info("Stopped recording.");
        }
    }
    updateHUD();
}

// 分段/保存
async function splitSegment() {
    if (currentTrackData.positions.length > 0) {
        // 保存前的起点和终点
        const startPos = currentTrackData.positions[0];
        const endPos = currentTrackData.positions[currentTrackData.positions.length - 1];

        const filename = await saveCurrentPath();
        if (filename) {
            steps.push({
                id: Date.now(),
                name: `Path ${currentStepIndex - 1}`,
                type: 'move',
                data: filename,
                start: [startPos.x.toFixed(0), startPos.y.toFixed(0)],
                end: [endPos.x.toFixed(0), endPos.y.toFixed(0)]
            });
            updateHUD();
            log.info(`Segment saved: ${filename}`);
        }
    } else {
        log.warn("No path data to save.");
    }
}

// 添加战斗标记
async function addCombatMarker() {
    await splitSegment();

    // 获取当前位置作为战斗点
    let pos = { x: 0, y: 0 };
    try {
        const p = genshin.getPositionFromMap();
        pos = { x: p.X, y: p.Y };
    } catch (e) { }

    steps.push({
        id: Date.now(),
        name: "Combat Event",
        type: 'fight',
        data: null,
        start: [pos.x.toFixed(0), pos.y.toFixed(0)],
        end: [pos.x.toFixed(0), pos.y.toFixed(0)]
    });
    updateHUD();
}

// OCR 识别
async function triggerOCR() {
    log.info("Triggering OCR...");
    // 暂停录制以防止OCR期间移动干扰
    const wasRecording = isRecording;
    isRecording = false;
    updateHUD();

    // 先保存当前路径
    await splitSegment();

    // 执行OCR
    await genshin.returnMainUi();
    const npcName = await extractNPCNameFromTask(); // 复用detection.js中的函数

    let pos = { x: 0, y: 0 };
    try { const p = genshin.getPositionFromMap(); pos = { x: p.X, y: p.Y }; } catch (e) { }

    steps.push({
        id: Date.now(),
        name: npcName ? `Talk: ${npcName}` : "Dialogue",
        type: 'ocr',
        data: npcName ? `Dialogue ${npcName}` : "Dialogue",
        start: [pos.x.toFixed(0), pos.y.toFixed(0)],
        end: [pos.x.toFixed(0), pos.y.toFixed(0)]
    });

    // 恢复录制
    if (wasRecording) {
        isRecording = true;
    }
    updateHUD();
}

// 显隐HUD
let hudVisible = true;
function toggleHUD() {
    hudVisible = !hudVisible;
    if (hudVisible) {
        htmlPanel.show(HUD_ID);
    } else {
        htmlPanel.hide(HUD_ID);
    }
}

// 保存当前路径到文件
async function saveCurrentPath() {
    if (currentTrackData.positions.length === 0) return null;

    // 路径优化
    optimizePathPoints();

    const filename = `${questName}-${currentStepIndex}.json`;
    const fullFolder = `process/${questLocation}/${questName}`;
    const fullPath = `${fullFolder}/${filename}`;

    // 确保目录存在 (BGI会自动创建，这里是形式上的)
    // ...

    // 更新文件头信息的名称
    currentTrackData.info.name = `${questName}-${currentStepIndex}`;

    file.WriteTextSync(fullPath, JSON.stringify(currentTrackData, null, 2));

    // 重置数据
    currentTrackData.positions = [];
    lastPosition = null;
    currentStepIndex++;

    return filename;
}

// 路径优化 (复用AutoStoryTranscribe逻辑)
function optimizePathPoints() {
    const positions = currentTrackData.positions;
    if (positions.length <= 2) return;

    // 1. RDP 简化
    const pointsForRdp = positions.map(p => ({ x: p.x, y: p.y }));
    const simplified = rdp(pointsForRdp, 2.0); // epsilon = 2.0

    // 找出保留的索引
    let keptIndices = new Set([0, positions.length - 1]); // 必留起止点

    // 映射回原始索引
    simplified.forEach(sp => {
        // 简单查找（注意：这在有重复坐标时可能不精准，但在RDP上下文中通常可行）
        // 更严谨的做法是在rdp函数中保留索引，但这里复用现有逻辑
        const idx = positions.findIndex(p => p.x === sp.x && p.y === sp.y);
        if (idx !== -1) keptIndices.add(idx);
    });

    // 2. 状态保护 (飞行、游泳、传送点)
    for (let i = 0; i < positions.length; i++) {
        const p = positions[i];
        // 传送点必留
        if (p.type === 'teleport' || p.optimize === false) keptIndices.add(i);

        // 状态转折点必留 (例如 跑->飞)
        if (i > 0 && positions[i].state !== positions[i - 1].state) {
            keptIndices.add(i - 1);
            keptIndices.add(i);
        }
    }

    // 重建数组
    const newPositions = Array.from(keptIndices).sort((a, b) => a - b).map(idx => {
        const p = positions[idx];
        p.id = idx + 1; // 重置ID
        return p;
    });

    currentTrackData.positions = newPositions;
}


// 主循环
async function mainLoop() {
    while (true) {
        try {
            // 1. 处理 HTML 发来的指令
            await handleClientActions();

            // 2. 录制逻辑
            if (isRecording && !isPaused) {
                if (isInMainUI()) {
                    await recordPosition();
                    await checkTeleport();
                }
            }

            // 3. 更新 HUD (每500ms更新一次，避免过于频繁)
            if (Date.now() - lastUpdateHUD > 500) {
                await updateHUD();
                lastUpdateHUD = Date.now();
            }
        } catch (e) {
            log.error("MainLoop Error: " + e.message);
        }

        await sleep(500);
    }
}

// 记录坐标
async function recordPosition() {
    try {
        const pos = genshin.getPositionFromMap();
        if (pos.X === 0 && pos.Y === 0) return;

        // 距离判定
        let dist = 0;
        if (lastPosition) {
            dist = distance({ x: pos.X, y: pos.Y }, lastPosition);
            if (dist < 1.0) return; // 距离太近不记录
        }

        // 状态判定 (复用 detection.js)
        const moveState = await checkAbnormalState();

        // 构建点数据
        const point = {
            id: currentTrackData.positions.length + 1,
            x: pos.X,
            y: pos.Y,
            action: "",
            move_mode: "walk", // 稍后在优化阶段可以 refined
            action_params: "",
            type: "path",
            state: moveState, // 临时保存用于优化
            timestamp: Date.now()
        };

        // 处理移动模式
        if (moveState === MOVE_STATE.FLY) point.move_mode = "fly";
        if (moveState === MOVE_STATE.CLIMB) point.move_mode = "climb";
        if (moveState === MOVE_STATE.SWIM) point.move_mode = "swim";
        // 普通 walk/dash 在优化阶段处理，暂记为 walk

        currentTrackData.positions.push(point);
        lastPosition = { x: pos.X, y: pos.Y };

        log.debug(`Recorded point: ${point.id} (${point.x.toFixed(1)}, ${point.y.toFixed(1)}) State: ${moveState}`);

    } catch (e) {
        log.error("Record Error: " + e.message);
    }
}

// 智能传送检测
async function checkTeleport() {
    // 逻辑：如果上一帧显示在地图界面，这一帧回到了主界面 -> 标记潜在传送
    // 这里我们简化：如果在主界面，且距离上一点突变 > 50米 -> 判定为传送，自动暂停
    if (!lastPosition) return;

    const pos = genshin.getPositionFromMap();
    const dist = distance({ x: pos.X, y: pos.Y }, lastPosition);

    if (dist > TELEPORT_THRESHOLD) {
        log.warn(`Dist jump detected: ${dist.toFixed(1)}m. Auto-pausing for confirmation.`);

        // 自动暂停
        isPaused = true;
        isRecording = false; // 严格暂停

        // 可以在这里自动标记上一个点为传送点，或者等待用户操作
        // 这里选择：弹出提示（通过HUD状态变色），用户手动F8恢复时，我们会重置lastPosition，
        // 这样下一次记录就是新的起点（传送后的点），这天然符合BGI路径逻辑（传送是断开的）。

        notification.Send("检测到长距离移动，录制已自动暂停。请按F8恢复录制。");
        updateHUD();
    }
}


// 处理客户端指令 (模拟双向通信)
async function handleClientActions() {
    try {
        // 读取 HTML 中的 window.clientAction 变量
        // log.debug("Evaluating window.clientAction...");
        const actionStr = await htmlPanel.eval(HUD_ID, "window.clientAction");
        let action = null;
        try {
            if (actionStr && actionStr !== "null") {
                action = JSON.parse(actionStr);
            }
        } catch (e) {
            // ignore parse error or null
        }

        if (action) {
            log.info("Client Action received: " + JSON.stringify(action));

            // 清除指令防止重复执行
            await htmlPanel.eval(HUD_ID, "window.clientAction = null");

            switch (action.type) {
                case 'delete_step':
                    const idx = steps.findIndex(s => s.id === action.id);
                    if (idx !== -1) {
                        steps.splice(idx, 1);
                        updateHUD();
                    }
                    break;
                case 'rename_step':
                    const step = steps.find(s => s.id === action.id);
                    if (step) {
                        step.name = action.newName;
                        updateHUD();
                    }
                    break;
                case 'update_task_name':
                    questName = action.name;
                    // updateHUD not needed as input handles itself, but good for sync
                    break;
                case 'undo':
                    // simple undo: pop last step
                    if (steps.length > 0) {
                        steps.pop();
                        updateHUD();
                    }
                    break;
                case 'hide_ui':
                    toggleHUD();
                    break;
            }
        }
    } catch (e) {
        // 忽略 eval 错误 (可能是窗口还没加载好)
    }
}

// 更新 HUD 状态 (改为 async 函数，正确 await eval 调用)
let isUpdatingHUD = false; // 防止重入

async function updateHUD() {
    // 防止重入：如果上一次更新还没完成，跳过本次
    if (isUpdatingHUD) return;
    isUpdatingHUD = true;

    try {
        updateKeysStatus();

        const pos = lastPosition || currentPos || { x: 0, y: 0 };
        // 如果没有 lastPosition (未录制), 获取当前位置用于显示
        let displayPos = pos;
        if (!lastPosition) {
            try {
                const p = genshin.getPositionFromMap();
                if (p.X !== 0) displayPos = { x: p.X, y: p.Y };
            } catch (e) { }
        }
        currentPos = displayPos;

        // 基础数据 (高频)
        const stateData = {
            isRecording: isRecording,
            taskName: questName,
            currentCoords: { x: displayPos.x, y: displayPos.y },
            keys: keysConfig
        };

        // 增量更新检测：只有当步骤数量发生变化时才发送步骤列表
        const currentStepCount = steps.length;

        // 如果有 dirty 标记 (e.g. rename) 或者长度变化
        if (currentStepCount !== lastSentStepCount || stepsDirty) {
            stateData.steps = steps.map(s => ({
                id: s.id,
                name: s.name,
                type: s.type,
                start: s.start,
                end: s.end
            }));
            lastSentStepCount = currentStepCount;
            stepsDirty = false;
        }

        const newStateStr = JSON.stringify(stateData);
        if (newStateStr !== lastSentHudData) {
            try {
                await htmlPanel.eval(HUD_ID, `updateState(${newStateStr})`);
                lastSentHudData = newStateStr;
            } catch (e) {
                // 忽略 eval 错误 (可能是窗口还没加载好或已关闭)
            }
        }
    } finally {
        isUpdatingHUD = false;
    }
}

// 更新步骤列表到 HUD (此函数已废弃，由 updateHUD 统一处理)
function updateStepListHUD() {
    // if (!hudVisible) return;
    // htmlPanel.eval(HUD_ID, `updateStepList(${JSON.stringify(steps)})`).catch(() => { });
}

// 脚本结束清理
function cleanUp() {
    if (hook) hook.Dispose();
    htmlPanel.closeAll();

    // 生成最终的 process.json
    if (steps.length > 0) {
        let processLines = [`作者：${author}`];
        steps.forEach(step => {
            if (step.type === 'path') {
                processLines.push(`地图追踪 ${step.data}`);
            } else if (step.type === 'fight') {
                processLines.push(`战斗`);
            } else if (step.type === 'dialogue') {
                processLines.push(step.data); // data is "Dialogue NPC" or just "Dialogue"
            }
        });

        const processPath = `process/${questLocation}/${questName}/process.json`;
        file.WriteTextSync(processPath, processLines.join('\n'));
        log.info(`Final process.json saved to ${processPath}`);
    }
}


// 启动 (使用 IIFE 确保 async 错误被捕获)
(async () => {
    try {
        await init();
    } catch (e) {
        log.error("Init Error: " + e.message);
        cleanUp();
    }
})();

// 保持运行直到用户手动停止 (ClearScript特性: 只要有未完成的异步任务或Timer，脚本就不会退出。
// 但这里我们用死循环 mainLoop 来保持)
