// 加载依赖 - detection.js 中已定义 MOVE_STATE, ELEMENT_STATE
eval(file.readTextSync("calculate.js"));
eval(file.readTextSync("detection.js"));

// 常量定义
const HUD_ID = "PathRecorderHUD";

// 移动模式常量（detection.js 未定义此常量）
const MOVE_MODES = {
    WALK: "walk",
    DASH: "dash",
    FLY: "fly",
    CLIMB: "climb",
    SWIM: "swim",
    JUMP: "jump"
};

const HUD_WIDTH = 800;
const HUD_HEIGHT = 400;
const TELEPORT_THRESHOLD = 20; // 传送检测阈值
const ANOMALY_THRESHOLD = 1000; // 异常距离阈值
const MAX_RECORDING_CYCLES = 72000; // 最大循环次数 (约10小时)
const strategyScript = "w(5)"; // 默认战斗策略脚本

// 配置读取 - 使用 let 以支持运行时修改
let questName = settings.questName || "Task";
let questLocation = settings.questLocation || "Mondstadt";
const author = settings.author || "User";
const autoFight = settings.autoFight !== false; // 默认启用自动战斗

// 快捷键配置
const keyRecord = settings.keyRecord || "F7";      // 开始/暂停录制
const keyRecordTp = settings.keyRecordTp || "F4";  // 开始录制(起点为传送点)
const keySplit = settings.keySplit || "F8";        // 路径分段
const keyOcr = settings.keyOcr || "F5";            // OCR对话
const keyFight = settings.keyFight || "F10";       // 战斗标记
const keyExport = settings.keyExport || "F9";      // 导出/结束录制

// 游戏菜单映射 (用于检测特定界面) - 延迟获取避免加载顺序问题
function getMenuStateMap() {
    return {
        "角色C": ELEMENT_STATE.C,
        "背包B": ELEMENT_STATE.B,
        "教程G": ELEMENT_STATE.G,
        "好友O": ELEMENT_STATE.O,
        "任务J": ELEMENT_STATE.J,
        "联机F2": ELEMENT_STATE.F2,
        "祈愿F3": ELEMENT_STATE.F3,
        "纪行F4": ELEMENT_STATE.F4
    };
}

// 快捷键配置显示
const keysConfig = [
    { key: keyRecord, label: '录制/暂停', active: false },
    { key: keyRecordTp, label: '录制(传送起点)', active: false },
    { key: keySplit, label: '路径分段', active: false },
    { key: keyOcr, label: 'OCR对话', active: false },
    { key: keyFight, label: '战斗标记', active: false },
    { key: keyExport, label: '导出结束', active: false }
];

// 全局状态
let isRecording = false;
let isPaused = false;
let lastEndType = null; // 上次录制结束类型: 'fight', 'dialogue', 'pause', 'save', 'story'
let startWithTp = false; // 起点是否为传送点
let justExitedMap = false; // 是否刚从地图界面退出
let wasInMap = false; // 是否曾进入地图界面
let cycleCount = 0; // 循环计数器

let currentTrackData = {
    info: {
        name: questName,
        type: "collect",
        author: author,
        version: "1.0",
        description: "Generated by PathRecorder",
        map_name: "Teyvat",
        bgi_version: "0.47.2"
    },
    positions: []
};
let steps = []; // 存储所有步骤 { name, type, data, info }
let currentStepIndex = 1;

let lastPosition = null;
let currentPos = { x: 0, y: 0 };
let lastUpdateHUD = 0;
let lastSentHudData = "";
let lastSentStepCount = -1;
let stepsDirty = false;

// process.json 数据
let processData = [];

// 从processData中寻找地图追踪文件的最大数字
function findMaxTrackNumber(data) {
    let maxNumber = null;
    const trackPattern = /地图追踪\s+([^-]+-)?(\d+)\.json/;

    for (const line of data) {
        const match = line.match(trackPattern);
        if (match && match[2]) {
            const currentNumber = parseInt(match[2]);
            if (maxNumber === null || currentNumber > maxNumber) {
                maxNumber = currentNumber;
            }
        }
    }
    return maxNumber;
}

// 分析process.json中的上次录制结束类型
function analyzeLastEndType(data) {
    if (!data || data.length === 0) {
        return null;
    }

    // 从最后一行开始向前查找
    for (let i = data.length - 1; i >= 0; i--) {
        const line = data[i].trim();

        // 跳过空行和作者信息
        if (!line || line.startsWith('作者：')) {
            continue;
        }

        // 分析不同的结束类型
        if (line === '战斗') {
            log.info("分析process.json: 上次录制以战斗结束");
            return 'fight';
        } else if (line.startsWith('对话')) {
            log.info("分析process.json: 上次录制以对话结束");
            return 'dialogue';
        } else if (line === '暂停') {
            log.info("分析process.json: 上次录制以暂停结束");
            return 'pause';
        } else if (line === '等待返回主界面') {
            log.info("分析process.json: 上次录制以剧情结束");
            return 'story';
        } else if (line.startsWith('地图追踪')) {
            log.info("分析process.json: 上次录制以保存结束");
            return 'save';
        }
    }

    log.info("分析process.json: 未找到明确的结束类型");
    return null;
}

// 初始化process.json数据（支持继续录制）
async function initProcessData() {
    const processPath = `process/${questLocation}/${questName}/process.json`;

    try {
        const existingContent = file.readTextSync(processPath);

        if (existingContent && existingContent.trim() !== '') {
            processData = existingContent.split('\n').filter(line => line.trim() !== '');
            log.info(`已读取现有process.json，共${processData.length}行`);

            // 确保第一行是作者信息
            const hasAuthor = processData.length > 0 && processData[0].startsWith('作者：');
            if (!hasAuthor) {
                processData.unshift(`作者：${author}`);
            }

            // 寻找地图追踪文件中最大的数字
            const maxTrackNumber = findMaxTrackNumber(processData);
            if (maxTrackNumber !== null) {
                currentStepIndex = maxTrackNumber + 1;
                log.info(`找到最大追踪文件数字: ${maxTrackNumber}，下一个文件段为: ${currentStepIndex}`);
            } else {
                log.info("未找到地图追踪文件，从第1段开始");
                currentStepIndex = 1;
            }

            // 分析上次录制结束类型
            lastEndType = analyzeLastEndType(processData);

            // 从processData恢复steps列表到HUD
            restoreStepsFromProcessData();
        } else {
            processData = [`作者：${author}`];
            currentStepIndex = 1;
            lastEndType = null;
            log.info("创建新的process.json，从第1段开始录制");
        }
    } catch (error) {
        processData = [`作者：${author}`];
        currentStepIndex = 1;
        lastEndType = null;
        log.info("文件不存在，创建新的process.json，从第1段开始录制");
    }
}

// 从processData恢复steps列表
function restoreStepsFromProcessData() {
    for (const line of processData) {
        if (line.startsWith('作者：')) continue;

        if (line.startsWith('地图追踪')) {
            const filename = line.replace('地图追踪 ', '').trim();
            steps.push({
                id: Date.now() + Math.random(),
                name: `Path: ${filename}`,
                type: 'move',
                data: filename,
                start: ['?', '?'],
                end: ['?', '?']
            });
        } else if (line === '战斗') {
            steps.push({
                id: Date.now() + Math.random(),
                name: 'Combat Event',
                type: 'fight',
                data: null,
                start: ['?', '?'],
                end: ['?', '?']
            });
        } else if (line.startsWith('对话')) {
            const npcName = line.replace('对话 ', '').trim();
            steps.push({
                id: Date.now() + Math.random(),
                name: `Talk: ${npcName || 'NPC'}`,
                type: 'ocr',
                data: line,
                start: ['?', '?'],
                end: ['?', '?']
            });
        } else if (line === '暂停') {
            steps.push({
                id: Date.now() + Math.random(),
                name: 'Paused',
                type: 'pause',
                data: null,
                start: ['?', '?'],
                end: ['?', '?']
            });
        } else if (line === '等待返回主界面') {
            steps.push({
                id: Date.now() + Math.random(),
                name: 'Wait MainUI',
                type: 'story',
                data: null,
                start: ['?', '?'],
                end: ['?', '?']
            });
        }
    }
    stepsDirty = true;
    log.info(`从process.json恢复了 ${steps.length} 个步骤`);
}

// 键鼠钩子
let hook = null;
let uiPollTimer = null;

// 初始化
async function init() {
    log.info("=== PathRecorder 路径录制系统 ===");

    // 0. 加载已有的process.json (支持继续录制)
    await initProcessData();

    // 显示当前状态
    const isFirstRecording = (currentStepIndex === 1 && lastEndType === null);
    if (isFirstRecording) {
        log.info("当前状态: 全新录制，从第1段开始");
    } else {
        log.info(`当前状态: 继续录制，从第${currentStepIndex}段开始`);
        if (lastEndType) {
            const endTypeNames = {
                'fight': '战斗',
                'dialogue': '对话',
                'pause': '暂停',
                'save': '保存',
                'story': '剧情'
            };
            log.info(`上次结束类型: ${endTypeNames[lastEndType] || lastEndType}`);
        }
    }

    // 1. 创建HUD（优先显示界面，让用户知道脚本已启动）
    log.info("创建 HTML HUD 面板...");
    htmlPanel.create(HUD_ID, HUD_WIDTH, HUD_HEIGHT);
    const htmlContent = file.readTextSync("status.html");
    htmlPanel.loadHtml(HUD_ID, htmlContent);
    htmlPanel.setLocked(HUD_ID, false);
    htmlPanel.setPosition(HUD_ID, 10, 10);
    htmlPanel.show(HUD_ID);

    // 给系统一点时间响应
    await sleep(100);

    // 2. 注册键鼠钩子（分步骤，避免阻塞）
    log.info("注册快捷键...");
    await sleep(50); // 让日志显示出来
    hook = new KeyMouseHook();
    await sleep(100); // 钩子初始化后给系统响应时间
    registerHotkeys();

    // 3. 延迟启用自动功能（非关键，可以稍后启用）
    await sleep(100);
    log.info("启用自动功能: AutoSkip / AutoPick / AutoEat");
    dispatcher.addTrigger(new RealtimeTimer("AutoSkip"));
    await sleep(50);
    dispatcher.addTrigger(new RealtimeTimer("AutoPick"));
    await sleep(50);
    dispatcher.addTrigger(new RealtimeTimer("AutoEat"));

    // 4. 显示快捷键说明
    log.info("=== 快捷键说明 ===");
    log.info(`${keyRecord}: 开始/暂停录制`);
    log.info(`${keyRecordTp}: 开始录制(起点为传送点)`);
    log.info(`${keySplit}: 路径分段保存`);
    log.info(`${keyOcr}: OCR对话标记`);
    log.info(`${keyFight}: 战斗标记`);
    log.info(`${keyExport}: 导出并结束录制`);
    log.info("F12: 显示/隐藏HUD");
    log.info("====================");

    // 5. 启动主循环
    log.info("启动主循环，等待用户操作...");
    await mainLoop();
}

// 注册快捷键
function registerHotkeys() {
    hook.OnKeyDown((keyCode) => {
        switch (keyCode) {
            case keyRecord:
                startWithTp = false;
                toggleRecording();
                break;
            case keyRecordTp:
                startWithTp = true;
                toggleRecording();
                break;
            case keySplit:
                splitSegment();
                break;
            case keyOcr:
                handleDialogue();
                break;
            case keyFight:
                handleFight();
                break;
            case keyExport:
                handleEndRecording();
                break;
            case 'F12':
                toggleHUD();
                break;
        }
    });
}

function updateKeysStatus() {
    keysConfig[0].active = isRecording && !startWithTp;
    keysConfig[1].active = isRecording && startWithTp;
}

// 切换录制状态 (暂停/恢复)
async function toggleRecording() {
    if (isRecording) {
        // 正在录制 -> 暂停
        await handlePause();
    } else {
        // 未录制/已暂停 -> 开始/恢复录制
        await handleResume();
    }
}

// 处理暂停
async function handlePause() {
    if (!isRecording) return;

    log.info("暂停录制...");

    // 保存当前路径
    if (currentTrackData.positions.length > 0) {
        const filename = await saveCurrentPath();
        if (filename) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, filename);
            processData.push(`地图追踪 ${filename}`);
        }
    }

    // 添加暂停标记
    processData.push("暂停");
    saveProcessData();

    addStepToList('pause', 'Paused', null);

    lastEndType = 'pause';
    isRecording = false;
    isPaused = true;

    updateHUD();
    log.info("录制已暂停，按 " + keyRecord + " 恢复");
}

// 处理恢复录制
async function handleResume() {
    log.info("恢复/开始录制...");

    // 确保在主界面
    if (!isInMainUI()) {
        await genshin.returnMainUi();
        await sleep(300);
    }

    if (!isInMainUI()) {
        log.warn("不在主界面，无法开始录制");
        return;
    }

    // 开始新的录制段
    await startNewRecording();

    isRecording = true;
    isPaused = false;
    lastEndType = null;

    updateHUD();

    const tpInfo = startWithTp ? " (起点为传送点)" : "";
    log.info(`录制已开始${tpInfo}，文件段: ${currentStepIndex}`);
}

// 开始新的录制段
async function startNewRecording() {
    log.info("开始新的录制段...");

    // 获取当前位置
    const position = genshin.getPositionFromMap();
    if (position.X === 0 && position.Y === 0) {
        log.warn("无法获取当前位置");
        return;
    }

    // 判断起始点类型
    const isFirstRecording = (currentStepIndex === 1);
    let initialPointType = "path";

    if (startWithTp || (isFirstRecording && settings.forceTpFirst)) {
        initialPointType = "teleport";
        log.info("起点设置为传送点");
    }

    // 检测初始状态
    const initialState = await checkAbnormalState();

    // 添加起始点
    const startPoint = {
        id: currentTrackData.positions.length + 1,
        x: position.X,
        y: position.Y,
        action: "",
        move_mode: "walk",
        action_params: "",
        type: initialPointType,
        state: initialState,
        timestamp: Date.now()
    };

    if (initialPointType === "teleport") {
        startPoint.optimize = false;
    }

    currentTrackData.positions.push(startPoint);
    lastPosition = { x: position.X, y: position.Y };

    log.info(`新录制段开始: 类型=${initialPointType}, 坐标=(${position.X.toFixed(1)}, ${position.Y.toFixed(1)})`);
}

// 分段/保存
async function splitSegment() {
    if (!isRecording) {
        log.warn("未在录制状态，无法分段");
        return;
    }

    if (currentTrackData.positions.length > 0) {
        const startPos = currentTrackData.positions[0];
        const endPos = currentTrackData.positions[currentTrackData.positions.length - 1];

        const filename = await saveCurrentPath();
        if (filename) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, filename, startPos, endPos);
            processData.push(`地图追踪 ${filename}`);
            saveProcessData();
            log.info(`路径分段已保存: ${filename}`);
        }
    } else {
        log.warn("当前无路径数据可保存");
    }
}

// 处理对话功能 (完整版: OCR + 点击NPC)
async function handleDialogue() {
    if (!isRecording) {
        log.warn("未在录制状态，无法添加对话标记");
        return;
    }

    log.info("处理对话功能...");

    // 暂停录制
    const wasRecording = isRecording;
    isRecording = false;

    // 保存当前路径
    if (currentTrackData.positions.length > 0) {
        const filename = await saveCurrentPath();
        if (filename) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, filename);
            processData.push(`地图追踪 ${filename}`);
        }
    }

    // 确保在主界面
    await genshin.returnMainUi();
    await sleep(200);

    // 从游戏界面OCR提取NPC名称
    const npcName = await extractNPCNameFromTask();

    if (npcName) {
        log.info(`提取到NPC名称: ${npcName}`);

        // 尝试在对话区域找到并点击NPC
        const dialogRegion = { X: 1150, Y: 300, WIDTH: 350, HEIGHT: 400 };
        let dialogResults = await Utils.easyOCR(dialogRegion);

        for (let i = 0; i < dialogResults.count; i++) {
            let text = dialogResults[i].text;
            let res = dialogResults[i];
            if (text.includes(npcName)) {
                log.info(`点击NPC选项: ${text}`);
                keyDown("VK_MENU");
                await sleep(500);
                click(res.x, res.y);
                leftButtonClick();
                keyUp("VK_MENU");
                break;
            }
        }

        processData.push(`对话 ${npcName}`);
        addStepToList('ocr', `Talk: ${npcName}`, `对话 ${npcName}`);
    } else {
        log.warn("未能提取到NPC名称，添加默认对话指令");
        processData.push("对话");
        addStepToList('ocr', 'Dialogue', '对话');
    }

    // 按F键触发剧情
    log.info("按下F键触发剧情");
    keyPress("F");
    await sleep(500);

    saveProcessData();
    lastEndType = 'dialogue';

    updateHUD();
    log.info("对话标记已添加，等待剧情结束...");

    // 等待返回主界面
    await waitForMainUI();

    // 自动恢复录制
    if (wasRecording) {
        isRecording = true;
        lastEndType = null;
        startWithTp = false;
        await startNewRecording();
        log.info("从对话返回，自动恢复录制");
    }

    updateHUD();
}

// 处理战斗功能 (完整版: 标记 + 自动战斗)
async function handleFight() {
    if (!isRecording) {
        log.warn("未在录制状态，无法添加战斗标记");
        return;
    }

    log.info("处理战斗功能...");

    // 保存当前路径
    await genshin.returnMainUi();

    if (currentTrackData.positions.length > 0) {
        const filename = await saveCurrentPath();
        if (filename) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, filename);
            processData.push(`地图追踪 ${filename}`);
        }
    }

    // 添加战斗标记
    processData.push("战斗");
    saveProcessData();

    let pos = { x: 0, y: 0 };
    try {
        const p = genshin.getPositionFromMap();
        pos = { x: p.X, y: p.Y };
    } catch (e) { }

    addStepToList('fight', 'Combat Event', null, pos, pos);

    lastEndType = 'fight';
    isRecording = false;

    updateHUD();
    log.info("战斗标记已添加");

    // 如果启用自动战斗，执行战斗
    if (autoFight) {
        log.info("启动自动战斗...");
        try {
            await dispatcher.runTask(new SoloTask("AutoFight"));
            log.info("自动战斗完成");
        } catch (e) {
            log.error("自动战斗出错: " + e.message);
        }
    }

    // 等待返回主界面后，用户需要手动按键恢复录制
    log.info("战斗结束，按 " + keyRecord + " 恢复录制");
}

// 处理结束录制/导出
async function handleEndRecording() {
    log.info("结束录制并导出...");

    // 保存最后的路径
    if (currentTrackData.positions.length > 0) {
        const filename = await saveCurrentPath();
        if (filename) {
            addStepToList('move', `Path ${currentStepIndex - 1}`, filename);
            processData.push(`地图追踪 ${filename}`);
        }
    }

    saveProcessData();
    lastEndType = 'save';
    isRecording = false;

    updateHUD();
    notification.send("PathRecorder: 录制已结束，process.json已保存");
    log.info("=== 录制已结束 ===");
    log.info(`保存位置: process/${questLocation}/${questName}/`);
    log.info(`共 ${steps.length} 个步骤`);
}

// 处理剧情界面
async function handleStoryInterface() {
    log.info("检测到剧情界面，处理特殊逻辑...");

    if (currentTrackData.positions.length > 0) {
        // 在最后一个路径点添加combat_script动作
        const lastIdx = currentTrackData.positions.length - 1;
        currentTrackData.positions[lastIdx].action = "combat_script";
        currentTrackData.positions[lastIdx].action_params = strategyScript;
        currentTrackData.positions[lastIdx].optimize = false;

        // 保存当前路径
        const filename = await saveCurrentPath();
        if (filename) {
            addStepToList('move', `Path ${currentStepIndex - 1} (Story)`, filename);
            processData.push(`地图追踪 ${filename}`);
            processData.push("等待返回主界面");
            saveProcessData();
        }
    }

    addStepToList('story', 'Wait MainUI', null);

    lastEndType = 'story';
    isRecording = false;

    log.info("剧情界面处理完成，等待返回主界面");
    updateHUD();

    // 等待返回主界面
    await waitForMainUI();

    // 自动恢复录制
    log.info("从剧情返回主界面，自动恢复录制");
    isRecording = true;
    lastEndType = null;
    startWithTp = false;
    lastPosition = null;
    await startNewRecording();

    updateHUD();
}

// 等待返回主界面
async function waitForMainUI() {
    log.info("等待返回主界面...");

    for (let i = 0; i < 1200; i++) { // 最多等待10分钟
        if (isInMainUI()) {
            log.info("已返回主界面");
            return true;
        }
        await sleep(500);
    }

    log.warn("等待返回主界面超时");
    return false;
}

// 添加步骤到列表
function addStepToList(type, name, data, startPos = null, endPos = null) {
    const step = {
        id: Date.now() + Math.random(),
        name: name,
        type: type,
        data: data,
        start: startPos ? [startPos.x?.toFixed(0) || '?', startPos.y?.toFixed(0) || '?'] : ['?', '?'],
        end: endPos ? [endPos.x?.toFixed(0) || '?', endPos.y?.toFixed(0) || '?'] : ['?', '?']
    };
    steps.push(step);
    stepsDirty = true;
}

// 显隐HUD
let hudVisible = true;
function toggleHUD() {
    hudVisible = !hudVisible;
    if (hudVisible) {
        htmlPanel.show(HUD_ID);
    } else {
        htmlPanel.hide(HUD_ID);
    }
}

// 保存当前路径到文件
async function saveCurrentPath() {
    if (currentTrackData.positions.length === 0) return null;

    // 路径优化
    await processTrackData();

    const filename = `${questName}-${currentStepIndex}.json`;
    const fullFolder = `process/${questLocation}/${questName}`;
    const fullPath = `${fullFolder}/${filename}`;

    // 更新文件头信息
    currentTrackData.info.name = `${questName}-${currentStepIndex}`;

    file.writeTextSync(fullPath, JSON.stringify(currentTrackData, null, 2));

    // 重置数据
    currentTrackData.positions = [];
    lastPosition = null;
    currentStepIndex++;

    return filename;
}

// 保存process.json
function saveProcessData() {
    const processPath = `process/${questLocation}/${questName}/process.json`;
    try {
        const processText = processData.join('\n');
        const success = file.writeTextSync(processPath, processText);
        if (success) {
            log.info(`process.json 已保存`);
        }
        return success;
    } catch (error) {
        log.error(`保存process.json失败: ${error.message}`);
        return false;
    }
}

// 处理收集到的路径数据
async function processTrackData() {
    log.info("处理路径数据...");

    // 1. 先优化点
    optimizePathPoints();

    // 2. 处理移动模式
    processMoveModes();

    // 3. 清理临时状态属性
    for (const pos of currentTrackData.positions) {
        delete pos.state;
        delete pos.timestamp;
        delete pos.__climb_points_count;
    }

    log.info("路径数据处理完成");
}

// 完整的移动模式处理
function processMoveModes() {
    log.info("处理移动模式和动作...");

    const positions = currentTrackData.positions;
    if (!positions || positions.length === 0) return;

    // 重置动作（保留 optimize=false 的点）
    for (const pos of positions) {
        if (pos.optimize !== false) {
            pos.action = "";
        }
    }

    // 分段处理飞行/游泳/攀爬
    let i = 0;
    while (i < positions.length) {
        const currentState = positions[i].state;

        // 飞行段：设置 fly 模式，终点添加 stop_flying
        if (currentState === MOVE_STATE.FLY) {
            let end = i;
            while (end + 1 < positions.length && positions[end + 1].state === MOVE_STATE.FLY) end++;
            for (let k = i; k <= end; k++) positions[k].move_mode = MOVE_MODES.FLY;
            positions[end].action = "stop_flying";
            log.debug(`飞行段: ${i} - ${end}, 添加stop_flying`);
            i = end + 1;
            continue;
        }

        // 游泳段：设置 swim 模式
        if (currentState === MOVE_STATE.SWIM) {
            let end = i;
            while (end + 1 < positions.length && positions[end + 1].state === MOVE_STATE.SWIM) end++;
            for (let k = i; k <= end; k++) positions[k].move_mode = MOVE_MODES.SWIM;
            log.debug(`游泳段: ${i} - ${end}`);
            i = end + 1;
            continue;
        }

        // 攀爬段：根据时长决定 jump 或 climb
        if (currentState === MOVE_STATE.CLIMB) {
            let end = i;
            while (end + 1 < positions.length && positions[end + 1].state === MOVE_STATE.CLIMB) end++;

            const climbPointsCount = positions[i].__climb_points_count || (end - i + 1);
            const climbDurationSeconds = climbPointsCount * 0.9;
            const climbMode = climbDurationSeconds < 15 ? MOVE_MODES.JUMP : MOVE_MODES.CLIMB;

            for (let k = i; k <= end; k++) positions[k].move_mode = climbMode;
            log.debug(`攀爬段: ${i} - ${end}, 时长=${climbDurationSeconds.toFixed(1)}s, 模式=${climbMode}`);

            // 长攀爬前回溯15单位，将dash改为walk
            if (climbMode === MOVE_MODES.CLIMB) {
                let backDistAccum = 0;
                for (let j = i - 1; j >= 0; j--) {
                    const segDist = distance(
                        { x: positions[j + 1].x, y: positions[j + 1].y },
                        { x: positions[j].x, y: positions[j].y }
                    );
                    backDistAccum += segDist;
                    if (backDistAccum >= 15) break;
                    if (positions[j].move_mode === MOVE_MODES.DASH) {
                        positions[j].move_mode = MOVE_MODES.WALK;
                    }
                }
            }

            i = end + 1;
            continue;
        }

        i++;
    }

    // 未设置模式的点根据距离判断dash/walk
    for (let idx = 0; idx < positions.length; idx++) {
        if (!positions[idx].move_mode || positions[idx].move_mode === "") {
            if (idx === 0) {
                positions[idx].move_mode = MOVE_MODES.WALK;
                continue;
            }
            const prev = positions[idx - 1];
            const dist = distance({ x: positions[idx].x, y: positions[idx].y }, { x: prev.x, y: prev.y });
            positions[idx].move_mode = dist > 10 ? MOVE_MODES.DASH : MOVE_MODES.WALK;
        }
    }
}

// 路径优化
function optimizePathPoints() {
    const positions = currentTrackData.positions;
    if (positions.length <= 2) return;

    const originalPoints = positions.map((p, index) => ({
        index: index,
        x: p.x,
        y: p.y,
        state: p.state
    }));

    // RDP简化
    const pointsForRdp = originalPoints.map(p => ({ x: p.x, y: p.y }));
    const simplified = rdp(pointsForRdp, 2.0);

    // 找出保留的点索引
    let keptIndices = simplified.map(sp => {
        return originalPoints.findIndex(op => op.x === sp.x && op.y === sp.y);
    }).filter(idx => idx !== -1);

    // 分段扫描，确保保留状态转换点
    const segments = [];
    let segStart = 0;
    for (let i = 1; i < originalPoints.length; i++) {
        if (originalPoints[i].state !== originalPoints[i - 1].state) {
            segments.push({ state: originalPoints[segStart].state, start: segStart, end: i - 1 });
            segStart = i;
        }
    }
    segments.push({ state: originalPoints[segStart].state, start: segStart, end: originalPoints.length - 1 });

    // 强制保留首尾
    if (!keptIndices.includes(0)) keptIndices.push(0);
    if (!keptIndices.includes(originalPoints.length - 1)) keptIndices.push(originalPoints.length - 1);

    // 强制保留传送点和不可优化点
    for (let idx = 0; idx < positions.length; idx++) {
        const pos = positions[idx];
        if (pos.type === "teleport" || pos.optimize === false) {
            if (!keptIndices.includes(idx)) {
                keptIndices.push(idx);
            }
        }
    }

    // 保留状态分段的起止点
    for (const seg of segments) {
        if (seg.state === MOVE_STATE.FLY || seg.state === MOVE_STATE.SWIM) {
            if (!keptIndices.includes(seg.start)) keptIndices.push(seg.start);
            if (!keptIndices.includes(seg.end)) keptIndices.push(seg.end);
        } else if (seg.state === MOVE_STATE.CLIMB) {
            if (!keptIndices.includes(seg.start)) keptIndices.push(seg.start);
            if (!keptIndices.includes(seg.end)) keptIndices.push(seg.end);
            // 移除攀爬段中间点
            keptIndices = keptIndices.filter(idx => !(idx > seg.start && idx < seg.end));
            // 记录攀爬点数
            positions[seg.start].__climb_points_count = seg.end - seg.start + 1;
        }
    }

    // 去重排序
    keptIndices = Array.from(new Set(keptIndices)).sort((a, b) => a - b);

    // 创建新数组
    const newPositions = keptIndices.map(idx => ({ ...positions[idx] }));
    newPositions.forEach((pos, idx) => { pos.id = idx + 1; });

    currentTrackData.positions = newPositions;
    log.info(`路径优化: ${positions.length} → ${newPositions.length} 个点`);
}

// 主循环
async function mainLoop() {
    while (cycleCount < MAX_RECORDING_CYCLES) {
        cycleCount++;

        // 每1000次输出进度
        if (cycleCount % 1000 === 0) {
            log.info(`系统运行: ${cycleCount}/${MAX_RECORDING_CYCLES} (${((cycleCount / MAX_RECORDING_CYCLES) * 100).toFixed(1)}%)`);
        }

        try {
            // 1. 处理 HTML 指令
            await handleClientActions();

            // 2. 检测界面状态 (仅在需要时)
            let elementState = ELEMENT_STATE.MAINUI;
            try {
                elementState = await checkElementState();
            } catch (stateErr) {
                // 界面检测失败时使用默认值，避免阻塞
            }

            // 追踪地图状态
            if (elementState === ELEMENT_STATE.MAP) {
                wasInMap = true;
            } else if (wasInMap && !justExitedMap) {
                justExitedMap = true;
                wasInMap = false;
                log.info("检测到离开地图界面，设置传送检测标志");
            }

            // 3. 剧情界面处理
            if (elementState === ELEMENT_STATE.Story) {
                if (isRecording) {
                    log.info("录制中检测到剧情界面");
                    await handleStoryInterface();
                } else {
                    log.info("非录制状态检测到剧情界面，等待返回主界面");
                    await waitForMainUI();
                }
            }

            // 4. 录制逻辑
            if (isRecording && !isPaused) {
                try {
                    if (isInMainUI()) {
                        await recordPosition();
                    }
                } catch (recErr) {
                    // 录制出错时继续循环
                }
            }

            // 5. 更新HUD
            if (Date.now() - lastUpdateHUD > 500) {
                await updateHUD();
                lastUpdateHUD = Date.now();
            }
        } catch (e) {
            log.error("MainLoop Error: " + e.message);
        }

        // 确保每次循环都有延迟，避免死循环
        await sleep(500);
    }

    // 达到最大循环次数
    log.warn(`已达到最大运行次数限制 (${MAX_RECORDING_CYCLES})，自动保存并结束`);
    if (isRecording && currentTrackData.positions.length > 0) {
        const filename = await saveCurrentPath();
        if (filename) {
            processData.push(`地图追踪 ${filename}`);
            saveProcessData();
        }
    }
}

// 记录坐标
async function recordPosition() {
    try {
        const position = genshin.getPositionFromMap();
        if (position.X === 0 && position.Y === 0) return;

        // 距离判定
        let dist = 0;
        if (lastPosition) {
            dist = distance({ x: position.X, y: position.Y }, lastPosition);
            if (dist < 1.0) return; // 距离太近不记录
        }

        // 检测移动状态
        const moveState = await checkAbnormalState();

        let pointType = "path";
        let optimizeFlag = true;

        // 从地图退出后的传送检测
        if (justExitedMap) {
            log.info(`刚从地图返回，检测首个点，距离: ${dist.toFixed(2)}`);

            if (dist > TELEPORT_THRESHOLD) {
                log.info("检测为传送点，获取精确坐标...");

                // 按M键打开大地图
                keyPress("M");
                await sleep(500);

                let bigMapPosition = null;
                let retryCount = 0;

                while (retryCount < 3 && !bigMapPosition) {
                    try {
                        bigMapPosition = genshin.getPositionFromBigMap();
                        if (bigMapPosition && bigMapPosition.X !== 0 && bigMapPosition.Y !== 0) {
                            log.info(`大地图精确坐标: (${bigMapPosition.X.toFixed(3)}, ${bigMapPosition.Y.toFixed(3)})`);
                            position.X = bigMapPosition.X;
                            position.Y = bigMapPosition.Y;
                            break;
                        } else {
                            throw new Error("获取到无效坐标");
                        }
                    } catch (error) {
                        retryCount++;
                        if (retryCount < 3) await sleep(200);
                    }
                }

                await genshin.returnMainUi();
                await sleep(100);

                pointType = "teleport";
                optimizeFlag = false;
            }

            justExitedMap = false;
        } else if (dist > ANOMALY_THRESHOLD && lastPosition) {
            // 异常距离检测（非地图退出情况）
            log.warn(`异常距离: ${dist.toFixed(2)} > ${ANOMALY_THRESHOLD}，可能是传送`);
            await checkTeleport();
            return;
        }

        // 构建点数据
        const point = {
            id: currentTrackData.positions.length + 1,
            x: position.X,
            y: position.Y,
            action: "",
            move_mode: "dash",
            action_params: "",
            type: pointType,
            state: moveState,
            timestamp: Date.now()
        };

        if (!optimizeFlag) {
            point.optimize = false;
        }

        // 处理移动模式
        if (moveState === MOVE_STATE.FLY) point.move_mode = "fly";
        if (moveState === MOVE_STATE.CLIMB) point.move_mode = "climb";
        if (moveState === MOVE_STATE.SWIM) point.move_mode = "swim";

        currentTrackData.positions.push(point);
        lastPosition = { x: position.X, y: position.Y };

        log.debug(`记录点 #${point.id}: (${point.x.toFixed(1)}, ${point.y.toFixed(1)}) 状态=${moveState}`);

    } catch (e) {
        log.error("recordPosition Error: " + e.message);
    }
}

// 智能传送检测
async function checkTeleport() {
    if (!lastPosition) return;

    const pos = genshin.getPositionFromMap();
    const dist = distance({ x: pos.X, y: pos.Y }, lastPosition);

    if (dist > TELEPORT_THRESHOLD) {
        log.warn(`传送检测: 距离跳变 ${dist.toFixed(1)}m`);

        // 保存当前路径
        if (currentTrackData.positions.length > 0) {
            const filename = await saveCurrentPath();
            if (filename) {
                addStepToList('move', `Path ${currentStepIndex - 1}`, filename);
                processData.push(`地图追踪 ${filename}`);
                saveProcessData();
            }
        }

        // 获取精确坐标
        keyPress("M");
        await sleep(600);

        let bigMapPosition = null;
        let retryCount = 0;

        while (retryCount < 3 && !bigMapPosition) {
            try {
                bigMapPosition = genshin.getPositionFromBigMap();
                if (bigMapPosition && bigMapPosition.X !== 0 && bigMapPosition.Y !== 0) {
                    break;
                }
                throw new Error("无效坐标");
            } catch (error) {
                retryCount++;
                if (retryCount < 3) await sleep(300);
            }
        }

        await genshin.returnMainUi();
        await sleep(200);

        // 添加传送点
        if (bigMapPosition && bigMapPosition.X !== 0) {
            lastPosition = { x: bigMapPosition.X, y: bigMapPosition.Y };

            const teleportPoint = {
                id: currentTrackData.positions.length + 1,
                x: bigMapPosition.X,
                y: bigMapPosition.Y,
                action: "",
                move_mode: "walk",
                action_params: "",
                type: "teleport",
                optimize: false,
                state: MOVE_STATE.NORMAL,
                timestamp: Date.now()
            };
            currentTrackData.positions.push(teleportPoint);
            log.info(`添加传送点: (${bigMapPosition.X.toFixed(1)}, ${bigMapPosition.Y.toFixed(1)})`);
        } else {
            lastPosition = { x: pos.X, y: pos.Y };
        }

        notification.send("检测到传送，已自动分段保存");
        updateHUD();
    }
}

// 处理客户端指令
async function handleClientActions() {
    try {
        const actionStr = await htmlPanel.eval(HUD_ID, "window.clientAction");
        let action = null;
        try {
            if (actionStr && actionStr !== "null") {
                action = JSON.parse(actionStr);
            }
        } catch (e) { }

        if (action) {
            log.info("Client Action: " + JSON.stringify(action));
            await htmlPanel.eval(HUD_ID, "window.clientAction = null");

            switch (action.type) {
                case 'delete_step':
                    const idx = steps.findIndex(s => s.id === action.id);
                    if (idx !== -1) {
                        steps.splice(idx, 1);
                        stepsDirty = true;
                        updateHUD();
                    }
                    break;
                case 'rename_step':
                    const step = steps.find(s => s.id === action.id);
                    if (step) {
                        step.name = action.newName;
                        stepsDirty = true;
                        updateHUD();
                    }
                    break;
                case 'update_task_name':
                    questName = action.name;
                    break;
                case 'undo':
                    if (steps.length > 0) {
                        steps.pop();
                        stepsDirty = true;
                        updateHUD();
                    }
                    break;
                case 'hide_ui':
                    toggleHUD();
                    break;
            }
        }
    } catch (e) { }
}

// 更新HUD状态
let isUpdatingHUD = false;

async function updateHUD() {
    if (isUpdatingHUD) return;
    isUpdatingHUD = true;

    try {
        updateKeysStatus();

        let displayPos = currentPos;
        if (!lastPosition) {
            try {
                const p = genshin.getPositionFromMap();
                if (p.X !== 0) displayPos = { x: p.X, y: p.Y };
            } catch (e) { }
        } else {
            displayPos = lastPosition;
        }
        currentPos = displayPos;

        // 提取路径点用于地图绘制 (最多保留最近100个点避免数据过大)
        const pathPoints = currentTrackData.positions.slice(-100).map(p => ({
            x: p.x,
            y: p.y,
            type: p.type || 'path'
        }));

        const stateData = {
            isRecording: isRecording,
            isPaused: isPaused,
            lastEndType: lastEndType,
            taskName: questName,
            currentCoords: { x: displayPos.x, y: displayPos.y },
            keys: keysConfig,
            cycleCount: cycleCount,
            pathPoints: pathPoints
        };

        if (steps.length !== lastSentStepCount || stepsDirty) {
            stateData.steps = steps.map(s => ({
                id: s.id,
                name: s.name,
                type: s.type,
                start: s.start,
                end: s.end
            }));
            lastSentStepCount = steps.length;
            stepsDirty = false;
        }

        const newStateStr = JSON.stringify(stateData);
        if (newStateStr !== lastSentHudData) {
            try {
                await htmlPanel.eval(HUD_ID, `updateState(${newStateStr})`);
                lastSentHudData = newStateStr;
            } catch (e) { }
        }
    } finally {
        isUpdatingHUD = false;
    }
}

// 脚本结束清理
function cleanUp() {
    if (hook) hook.Dispose();
    htmlPanel.closeAll();

    if (processData.length > 1) {
        saveProcessData();
        log.info("Final process.json saved.");
    }
}

// 启动
(async () => {
    try {
        await init();
    } catch (e) {
        log.error("Init Error: " + e.message);
        cleanUp();
    }
})();
